### ISSUE TITLE
Test on windows

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/crayon#10]
In progress on Azure

**Comment by faridcher** [comment]
is windows powershell  supported? I can output colored text in powershell (cmd) using:
```r
cat("\033[32;1m OK \033[0m\n")
```
but crayon functions don't work!

**Comment by gaborcsardi** [comment]
We need to add it to the detection then.

Until then, you can set the `ConEmuANSI` environment variable to `ON`. This should give you 8 colors.

**Comment by gaborcsardi** [comment]
Can you please open a new issue for this? Thanks.
