### ISSUE TITLE
(Automatically) display hexadecimal strings in RStudio console in their respective color?

### ISSUE THREAD

**Issue by SchmidtPaul** [r-lib/crayon#102]
I am aware that crayon can make the RStudio console output appear in all kinds of colors when manually asked to do so with functions such as blue().
What would really be awesome, however, would be a package or RStudio Addin that automatically colors strings in the console if they are color character names or hexadecimal strings. Take this vector as an example:
```
c("blue", "#ff00ff", "#CCE6FF")
```
printing it in the console would look like this
![image](https://user-images.githubusercontent.com/31928213/99059759-4904a100-259f-11eb-9fd9-345b8f526d23.png)

Do you think there is a way to make this happen?
[Link to same question on stackoverflow](https://stackoverflow.com/questions/64787148/automatically-display-hexadecimal-strings-in-rstudio-console-in-their-respecti)

**Comment by gaborcsardi** [comment]
crayon cannot do this, when you type `c("blue", "#ff00ff", "#CCE6FF")` no crayon code runs. I think you probably want this feature: https://github.com/rstudio/rstudio/issues/5424

**Comment by SchmidtPaul** [comment]
Yes. Yes, thanks for mentioning it!
