### ISSUE TITLE
No color in RStudio

### ISSUE THREAD

**Issue by jennybc** [r-lib/crayon#104]
As of 07635d7b0bc1bbf0ea061623ecbe6ab563b2107c, I no longer have colors in RStudio.

My RStudio version is 1.4.1043 (on macOS).

**Comment by jennybc** [comment]
Whether this fixes it for me depends on how I install crayon.

If I use `pak::pak()`, I get colour in RStudio.

If, from the crayon project, I do *Build > Install and Restart*, I do not get colour in RStudio.

**Comment by gaborcsardi** [comment]
5f7af841b921eb21592d3a9a92cc0efaf47ea89e should fix this.

**Comment by jennybc** [comment]
OK yes, the last several commits have cleared things up.
