### ISSUE TITLE
HTTP status was '404 Not Found'

### ISSUE THREAD

**Issue by EmilyKubicek** [r-lib/crayon#108]
Partial result of attempting to install devtools:

```
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/crayon_1.4.0.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/crayon_1.4.0.tgz'
Warning in install.packages :
  download of package ‘crayon’ failed
```

After the recent update to this package, when downloading as a dependency for devtools, I am unable to do so. When manually following the link to  'https://cran.rstudio.com/bin/macosx/contrib/4.0/crayon_1.4.0.tgz' you can also see that it's not found.

**Comment by charlottewright** [comment]
I am having the same issue while downloading crayon as a dependency for tidyverse.

**Comment by jocean243** [comment]
Hello, I just fix this problem by doing it manually from here:

https://cran.r-project.org/web/packages/crayon/index.html

1. download a crayon 1.3.4.tgz (or the other one with tgz) 
2. go to Rstudio, find "packages" at right
3. there should be an "install" button below it
4. press "install"
5. in "install from", the default is "CRAN", change it to "Package Archive File"
6. press "browse" if the file management window doesn't show up
7. select the ???.tgz you just downloaded
8. install

**Comment by EmilyKubicek** [comment]
Does that fix the problem or simply avoid it? I'm currently creating/test a package that I want beginners to be able to open and I cannot ask them to do this upon install.

**Comment by jocean243** [comment]
I think this method just avoids the 404 page, since the solution should be somehow bring back the original link or transfer to the new link in CRAN installation method (I don't know how to do this exactly, but I suppose when using install.packages(???), it will be directed to a valid page)

**Comment by EmilyKubicek** [comment]
Anything that leads back to the updated link (https://cran.rstudio.com/bin/macosx/contrib/4.0/crayon_1.4.0.tgz) does not work (even if you manually paste in the link with install.packages()). Thus, I think the issue is at a maintainer level, and something about its communication with CRAN needs to be fixed at that internal level.

I had an issue similar to this with _withr_ and am now also seeing it with _rappdirs_ (_devtools_ having reliance on both) and it just so happens that these packages were also updated within the last week ☹️  However, the _withr_ maintainers updated their package a second time within the week and it now works great, no 404 error.

**Comment by gaborcsardi** [comment]
This is a bug in CRAN, so we can't do much about it: 
https://stat.ethz.ch/pipermail/r-sig-mac/2021-January/013884.html

Use can use the canonical macOS CRAN machine as a workaround:
```r
install.packages("crayon", repos = c(CRAN = "https://mac.r-project.org/"))
```

**Comment by ale-yanez** [comment]
Thank you very much @gaborcsardi ... that worked for me! Other possible solution could be re install an older version of R maybe? (That one was my last option) But the canonical macOS CRAN worked pretty good!
