### ISSUE TITLE
num_ansi_colors (v1.4.0) returns NA with Rstudio server

### ISSUE THREAD

**Issue by TBradley27** [r-lib/crayon#112]
Hello there,

Many thanks for this package!

It seems that I am having some compatibility issues between v1.4.0 of crayon and version 1.0.143 of RStudio (RStudio server implementation). This is taking place within an ubuntu operating system.

I am afraid `crayon::num_ansi_colors()` returns a value of NA when I am using RStudio.

This is with an underlying R version of 3.6.3. I tested the same function on the R binary itself on the command line (i.e. without RStudio) - and the value returned was 256.

I discovered this error when trying to use/load tidyverse packages which started to fail because of this

Update: After downgrading to v1.3.4 I am now able to load/use tidyverse packages once again

**Comment by gaborcsardi** [comment]
Thanks, I can reproduce this. Will be fixed in a new crayon release in about a week.

Until then a workaround is a downgrade, or setting this option in your `.Rprofile`:
```
options(crayon.enabled = FALSE)
```

**Comment by trevorld** [comment]
I'm noticing on my server that this bug may also occur in ``interactive()`` use in base R (not RStudio).  In particular ``testthat::test_package()`` would choke in interactive use but provide pretty color output when called via ``Rscript -e``.  Weirdly ``crayon::num_ansi_colors()`` returns 256 in my terminal without error but reports an error within the interactive call to ``test_package()``.  Your ``options(crayon.enables = FALSE)`` does work as a workaround for me:

```r
> testthat::test_package(package="crayon")
Error in clienv$num_colors[[std]] : subscript out of bounds

Enter a frame number, or 0 to exit   

 1: testthat::test_package(package = "crayon")
 2: test_dir(test_path, package = package, reporter = reporter, ..., load_packa
 3: test_files(test_dir = path, test_paths = test_paths, test_package = package
 4: test_files(test_dir = test_dir, test_package = test_package, test_paths = t
 5: test_files_reporter(reporter)
 6: ListReporter$new()
 7: initialize(...)
 8: super$initialize()
 9: crayon::has_color()
10: num_ansi_colors()
11: clienv$num_colors[[std]] %||% detect_tty_colors()
```
