### ISSUE TITLE
Colors no longer work in RStudio's console with the .First() function 

### ISSUE THREAD

**Issue by MAC-GH** [r-lib/crayon#117]
Hello,

I'm using a .Rprofile file with something like:

.First <- function() {
    library(crayon)
    cat(file = stderr(), yellow$bold("\nWelcome to your personal .Rprofile!\n"))
}

.Last <- function() {
    cat(file = stderr(), cyan$bold("\nGoodbye from your personal .Rprofile!\n"))
    Sys.sleep(2)
}

After the version 1.3.4 the .First() function outputs everything in red and ignores the style whatever the color/style combination I use. The .Last() function still outputs correctly. This happens with several different builds of 64 bits Windows 10, several R versions (3.3.0, 3.5.3, 3.6.1, 4.0.4) and different versions of RStudio (1.2.xxxx or newer and all configured with "Show ANSI colors").

Could you, please, have a look and let me know if you require additional info ?

Thanks and regards,
Jimmy

**Comment by gaborcsardi** [comment]
I can indeed reproduce this on Windows, seems like a bug, will fix soon. You can force the colors for now if you want.
