### ISSUE TITLE
colors different on pkgdown/github site?

### ISSUE THREAD

**Issue by SchmidtPaul** [r-lib/crayon#118]
I just started using `crayon::blue()` etc. for my function's `cat()` output e.g. [here](https://github.com/SchmidtPaul/CitaviR/blob/ea4329067f9c602573b3bd2229658faca478ca09/R/find_potential_dups.R#L68). In RStudio Console output it looks nice (see Fig. 1). But [in the html file](https://github.com/SchmidtPaul/CitaviR/blob/ea4329067f9c602573b3bd2229658faca478ca09/docs/reference/find_potential_dups.html#L184) it is not the same blue so that it looks bad on [the github site](https://schmidtpaul.github.io/CitaviR/reference/find_potential_dups.html#examples) (see Fig. 2). I am using an [pkgdown/extra.css](https://github.com/SchmidtPaul/CitaviR/blob/ea4329067f9c602573b3bd2229658faca478ca09/pkgdown/extra.css). 

What would be the best way to get similar/better colors for the github site output?

### Fig. 1
![image](https://user-images.githubusercontent.com/31928213/111469360-e5de7300-8726-11eb-9539-43a2196fcee1.png)

### Fig. 2
![image](https://user-images.githubusercontent.com/31928213/111468376-c5fa7f80-8725-11eb-9ce4-249c07dbc909.png)

### reprex
``` r
# devtools::install_github('SchmidtPaul/CitaviR')
library(CitaviR)

path <- example_xlsx("3dupsin5refs.xlsx")
CitDat <- read_Citavi_xlsx(path) %>%
  find_obvious_dups() %>%
  find_potential_dups()
```
<sup>Created on 2021-03-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by gaborcsardi** [comment]
crayon does not deal with the HTML conversion, and it cannot control how the HTML colors are chosen. This is probably up to pkgdown, or downlit or fansi, or a subset of them.

I did not find any issues about this in the pkgdown or downlit issue trackers, but maybe I have overlooked something. Nevertheless you could try opening an issue in r-lib/downlit.

**Comment by youngwoos** [comment]
@SchmidtPaul maybe it helps?
https://logfc.wordpress.com/2020/07/20/rmarkdown-and-terminal-colors/

**Comment by gaborcsardi** [comment]
@youngwoos pkgdown and/or downlit colour the text themselves, no need to do it manually.
