### ISSUE TITLE
red$bold(X) results in : Error in gsub: input string 1 is invalid UTF-8

### ISSUE THREAD

**Issue by RoelRotti** [r-lib/crayon#129]
When I try to paste 'crayon::red$bold' to a a message (X) like:

`Return_message <- paste(crayon::red$bold(X),
                                crayon::cyan(Y), sep = "\n")`

I get the following error:

`Error in gsub(st$close, st$open, text, fixed = TRUE) : 
  input string 1 is invalid UTF-8`

which when traced seems to come from the 'red$bold' function.

While upon inspection X does not seem to be invalid utf-8, I have also tried manually converting it like:

`        X<- stringi::stri_enc_toutf8(X, is_unknown_8bit = TRUE, validate = TRUE)
`
and 

` X<- stringi::stri_enc_toutf8(X, is_unknown_8bit = FALSE, validate = FALSE)`

But I keep getting the same error, would you have any idea why?

**Comment by gaborcsardi** [comment]
Can you try to create a reproducible example that fails?

**Comment by RoelRotti** [comment]
I have tried really hard to produce a reproducible example but can't seem to get it. I do know that switching from crayon to CLI seems to solve the problem, so it does seem to be somewhere in crayon

**Comment by gaborcsardi** [comment]
It is something like this:

```r
x <- "\xfc"
Encoding(x) <- "UTF-8"
crayon::bold(crayon::red(x))
#> Error in gsub(st$close, st$open, text, fixed = TRUE) :
#>   input string 1 is invalid UTF-8
```

While we can "fix" this in crayon, it probably indicates an error in your code, in that it should not produce strings with an invalid encoding.
