### ISSUE TITLE
Color detection Github Actions

### ISSUE THREAD

**Issue by assignUser** [r-lib/crayon#130]
Thanks for the package,  everything is more fun in color :partying_face: 

The gha logs support[ 24bit color](https://github.blog/2020-09-23-a-better-logs-experience-with-github-actions/) but crayon does not detected it. I have forced it using `cli.num_colors` and that works fine:
![image](https://user-images.githubusercontent.com/16141871/150678329-6a809366-a098-4430-a413-d8504f978d05.png)

Setting the option works for now but offical support would be nice :)

**Comment by assignUser** [comment]
Actually just detecting if the envvar `GITHUB_ACTIONS` is set would probably be the easiest way to do this.

**Comment by gaborcsardi** [comment]
It is unlikely that we can solve this, because if we force the colors on it will break testthat edition 2, and probably other things as well.

**Comment by assignUser** [comment]
Ah, don't want to break anything ofc. I just had a look at your detection method, would setting the envvar `COLORTERM="truecolor"` have the same issues or would it be "safe"?

**Comment by gaborcsardi** [comment]
Good idea re `COLORTERM`, but it'll only work if `isatty(stdout())` is `TRUE` on GHA, and it is probably not.

**Comment by assignUser** [comment]
You are right, it is false on GHA :( https://github.com/actions/runner/issues/241

Well I guess I'll use `R_CLI_NUM_COLORS` then. Thanks for your quick help!
