### ISSUE TITLE
Potential NAMESPACE/import issue?

### ISSUE THREAD

**Issue by pbreheny** [r-lib/crayon#133]
Hello,

I'm not sure why this issue seems to only affect me, but I am unable to install **crayon** from CRAN or github:

```
> install.packages('crayon')
trying URL 'https://mirror.las.iastate.edu/CRAN/src/contrib/crayon_1.5.0.tar.gz'
Content type 'application/x-gzip' length 40099 bytes (39 KB)
==================================================
downloaded 39 KB

* installing *source* package ‘crayon’ ...
** package ‘crayon’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in read.table("tools/ansi-palettes.txt", comment = ";", stringsAsFactors = FALSE) : 
  could not find function "read.table"
Failed with error:  ‘unable to load R code in package ‘crayon’’
Error: crayon package is not installed
Execution halted
ERROR: lazy loading failed for package ‘crayon’
```

The issue is that in the function `ansi_palettes()`, the call to `read.table()` doesn't explicitly specify the namespace. If I clone the source code and change `read.table()` to `utils::read.table()`, everything installs fine. Again, no idea why this works for some and not others, but maybe you want to explicitly specify the namespace here, as it appears to affect installation on some R setups (and is probably better coding practice)?

**Comment by gaborcsardi** [comment]
It works for the people that load the utils package from the profile, usually through another package.
