### ISSUE TITLE
Nested `reset` behaves differently to other styles

### ISSUE THREAD

**Issue by brodieG** [r-lib/crayon#35]
Compare:

```
cat(bgGreen("hello ", reset("there"), "yo"), "\n")
cat(bgGreen("hello ", bgRed("there"), "yo"), "\n")
```

As an image:

![crayon](https://cloud.githubusercontent.com/assets/6105908/14748635/c3555ae6-0888-11e6-812d-00d06a186392.PNG)

Ideally the "yo" would be green for the first expression too.  I think the problem might be at [this line](https://github.com/gaborcsardi/crayon/blob/master/R/machinery.r#L10) whereby you replace any prior closing tags with opening tags and move the closing tags to the end.  However, because the closing tag for `reset` doesn't match any closing tags for any of the other styles, this doesn't work.

A possible solution would be to replace the closing tag for `reset` with every possible closing tag concatenated, which I _think_ should work with fairly minimal changes, though will add a bunch of stray closing tags whenever one uses `reset`.  That shouldn't affect anything though.

Let me know if you'll consider a pull request for this.

**Comment by gaborcsardi** [comment]
Essentially embedding works for the same type of styles, e.g. foreground colors are a type of style. Different style types are orthogonal. E.g. 

```r
green("hello ", bold("there"), "yo")
#> [1] "\033[32mhello  \033[1mthere\033[22m yo\033[39m"
```
is all green, but in the middle also bold. The boldness does not turn off the greenness. 

`reset` is a special style that does not play well with any other styles in terms of embedding. 

I guess we could have a `resetColor` and a `resetBgColor` style, and this would reset only the fg and bg colors and these would work well with embedding.

**Comment by brodieG** [comment]
If I get around to it I'll mock up the example I'm thinking of.  Embedding for the same type of styles does not work in plain ANSI.  You awesomely got it to work for crayon by moving existing closing escape sequences.  I _think_ we can do the same for reset so long as we're willing to throw in every possible type of closing sequence.  Either way, it's on me to mock it up and I think it's going to be kinda far down the priority list.  Feel free to close the issue if having an open issue is annoying to you since I'm unlikely to get to this anytime soon.

**Comment by gaborcsardi** [comment]
OK. I might implement `resetColor` and `resetBgColor` in the meanwhile, I think those still make sense.

**Comment by gaborcsardi** [comment]
I am going to close this now, please reopen if you want to work on it.

**Comment by brodieG** [comment]
Sounds good.
