### ISSUE TITLE
missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by lindauer** [r-lib/crayon#39]
I'm getting an installation error and am stumped. Any idea what the problem is and how to fix it?

```
> install.packages("crayon")
Installing package into ‘/home/xxx/R/x86_64-redhat-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://mirrors.nics.utk.edu/cran/src/contrib/crayon_1.3.2.tar.gz'
Content type 'unknown' length 656168 bytes (640 KB)
==================================================
downloaded 640 KB

* installing *source* package ‘crayon’ ...
** package ‘crayon’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in if (inside_emacs() && emacs_version()[1] >= 23) { : 
  missing value where TRUE/FALSE needed
Error : unable to load R code in package ‘crayon’
ERROR: lazy loading failed for package ‘crayon’
* removing ‘/home/xxx/R/x86_64-redhat-linux-gnu-library/3.3/crayon’

The downloaded source packages are in
    ‘/tmp/RtmpIVwQXr/downloaded_packages’
Warning message:
In install.packages("crayon") :
  installation of package ‘crayon’ had non-zero exit status
>
```

Thanks,
Brian

**Comment by gaborcsardi** [comment]
Are you in Emacs? It seems to be a bug in the detection of the emacs version. You can word around it by setting the `INSIDE_EMACS` environment variable. This is how mine is set:
```r
> Sys.getenv("INSIDE_EMACS")
[1] "24.4.50.1,comint"
```

**Comment by lindauer** [comment]
No, I'm running R from a bash command line. My INSIDE_EMACS environment variable is unset. Should I set it to something?

**Comment by gaborcsardi** [comment]
Is your `EMACS` environment variable set by any chance?

You don't need to set anything, this is a bug in crayon, I am just trying to find out how it happened....

**Comment by lindauer** [comment]
That was it. I had to unset my EMACS environment variable first.

**Comment by gaborcsardi** [comment]
That makes sense. `crayon` just assumed that if `EMACS` was set, then R is running inside emacs. Still this is a bug, it should not fail.

**Comment by gaborcsardi** [comment]
I believe that this is fixed in the dev version.
