### ISSUE TITLE
Increase Coverage

### ISSUE THREAD

**Issue by brodieG** [r-lib/crayon#42]
I looked into increasing coverage and it seems like there is a bit of code that isn't in use, such as:
- `data_frame`, which I think has been mostly superseded by the switch to matrices that I made a while back
- the code in [disposable.r](https://github.com/gaborcsardi/crayon/blob/master/R/disposable.r), which as far as I can tell isn't currently in use?

I can submit a PR addressing those plus other low hanging fruit if you're interested.  I imagine there is a reason why `disposable.r` is in the package though.

**Comment by gaborcsardi** [comment]
`disposable.r` is actually used, here: https://github.com/gaborcsardi/crayon/blob/e608c57d0785ce3e269bf2c80a4b30ccb489ce3e/tests/testthat/test-styles.r#L14

**Comment by brodieG** [comment]
Ah, that is the skipped test, makes sense.

**Comment by gaborcsardi** [comment]
I have increased it a bit. Will do more later.
