### ISSUE TITLE
crayon:::has_color() returns FALSE when an output sink is active

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/crayon#48]
# Issue
`crayon::red("foo")` etc. fail to generate color codes when there is an active "output" sink.  This is because `crayon:::has_color()` returns FALSE in such cases, which appears to be due to the `isatty(stdout())` test.  "Message" sinks does not cause this problem.

# Troubleshooting

## No active output sink
```r
> crayon:::has_color()
[1] TRUE
> isatty(stdout())
[1] TRUE
```

## Active output sink
```r
> sink(tempfile())
> x <- crayon:::has_color()
> y <- isatty(stdout())
> sink()
> x
[1] FALSE
> y
[1] FALSE
```

# Details
```r
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0 crayon_1.3.2  
```

**Comment by gaborcsardi** [comment]
The idea is that you will print those strings to stdout ASAP, and if stdout does not support color, then we don't use the ANSI escape codes. So this is as designed.

Most programs work the same way, e.g. just try 
```
ls -G
ls -G > /tmp/x
```

If you want to force the ANSI sequences, use the `crayon.enabled.` and `crayon.colors` options. E.g. 
```
withr::with_options(
  c(crayon.enabled = TRUE, crayon.colors = 256),
  red("I am red")
)
```

**Comment by HenrikBengtsson** [comment]
I see; makes sense.

Then a follow up, shouldn't there be test against `stderr()` if you "plan" to print to stderr?  I understand this is not easy to detect / support automatically; maybe an argument `output = "stdout"`?

FYI, I bumped into this when trying to conditionally display `yellow("1 output sink")` to a customized `prompt` function.  I did find the workaround where I do `if (crayon:::has_color()) options(crayon.enabled = TRUE)` when I first set up the prompt during `.Rprofile` startup (where I can safely assume no sinks are active).

**Comment by gaborcsardi** [comment]
> maybe an argument output = "stdout"?

argument to what function?

Maybe it could be an option, e.g. `crayon.output`, but that will be cumbersome to change every time...

**Comment by HenrikBengtsson** [comment]
>> maybe an argument output = "stdout"?

> argument to what function?

agree == "maybe" ;)  In worst case, it's needed for all functions calling `has_color()` ... very tedious to use.

Could such an option be encapsulated in a convenient `for_stderr()` wrapper, e.g. `for_stderr(red("foo"))`?  (not sure if `with_stderr()` is good here).

**Comment by gaborcsardi** [comment]
`for_stderr` is a good idea. How about calling it `color_stderr` ?

We could also have `with_color` to shorten the `with_options` call above.

**Comment by HenrikBengtsson** [comment]
`color_stderr()` is better, but like `with_color()` even more. Not sure what the argument / option name should be, e.g. `target`, `type` (cf. `sink()`), ...?

For the output target, can see something like the following use cases:

* `with_color(..., target = "stdout"))`
* `with_color(..., target = "stderr"))`
* `with_color(..., target = c("stdout", "stderr")))`  - outputting to both(?)
* `with_color(..., target = "prompt"))` - neither stdout nor stderr, but prompt and readline-ish output (non-sinkable)
* `with_color(..., target = "none"))`  - disable coloring
* `with_color(..., target = "always"))` - enable coloring regardless of support(?)

**Comment by gaborcsardi** [comment]
Yeah, sg. like that.

**Comment by gaborcsardi** [comment]
OK, I decided not to do this for the next patch release. It is probably not commonly needed, and I am not yet sure what would be the right way to do. For now, please force color as a workaround.
