### ISSUE TITLE
Crayon fails to detect correct number of terminal colors in Rstudio

### ISSUE THREAD

**Issue by s-fleck** [r-lib/crayon#56]
`crayon::num_colors()` sometimes returns just `1`, which causes undesired results with `make_style()`. The error occurs for me after building a package with ctrl+shift+b, though I do not know if this is consistent way to reproduce the error.

Using `crayon::num_colors(forget = TRUE)` always returns the correct number of colors. Maybe this should be the default?

I am using Rstudio Version 1.1.338

**Comment by gaborcsardi** [comment]
We cannot make `forget = TRUE` the default, because it is slow. 

This probably happens because `crayon` is loaded from an R profile, and at this point, `rstudioapi` is not ready to let `crayon` know about the color support. We'll try to work around this with the RStudio IDE team.

**Comment by gaborcsardi** [comment]
I think this is fixed now.

**Comment by s-fleck** [comment]
Thanks!
