### ISSUE TITLE
crayon::`col_substr()<-`

### ISSUE THREAD

**Issue by krlmlr** [r-lib/crayon#57]
A replacement version for `substr()` is useful for colformat to truncate a string and replace the last character(s) with an ellipsis. The current code doesn't apply the styling of the previous text to the newly added ellipsis:

```
  x[too_wide] <- paste0(crayon::col_substr(x[too_wide], 1, width - 1), "\u2026")
```

**Comment by gaborcsardi** [comment]
Deferred to the next version, sorry.

**Comment by gaborcsardi** [comment]
I think this can be probably done with fansi, so closing this.
