### ISSUE TITLE
crayon::col_strwrap()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/crayon#58]
needed for tibble.

**Comment by gaborcsardi** [comment]
and a lot of other things. There is an implementation in `ansistrings`.

**Comment by krlmlr** [comment]
I keep forgetting. Would you recommend migrating to ansistrings now?

**Comment by gaborcsardi** [comment]
Not yet. `ansistrings` will happen, but don't know when.....

**Comment by gaborcsardi** [comment]
Deferred to the next version, sorry

**Comment by gaborcsardi** [comment]
This can be done with fansi now.
