### ISSUE TITLE
Crayon and old R version (3.2.5)

### ISSUE THREAD

**Issue by economistgame** [r-lib/crayon#66]
Hello, I test one function in a university server with version is 3.2.5 and when execute this lines:

warningstyle <- crayon::make_style(WarningStyle = rgb(1,0.2,0), bg = FALSE)
errorstyle <- crayon::make_style(ErrorStyle = "red", bg = FALSE)
successstyle <- crayon::make_style(SucessStyle = rgb(0,1,0), bg = FALSE)

Makes this error
Error in my_styles[[name]] <<- ansi_seq : 
  no se puede cambiar el valor de un vínculo bloqueado para  'my_styles'
Thanks for your time. When  I execute a predefined style appear without color (black)

**Comment by gaborcsardi** [comment]
I can't reproduce this:
```
> getRversion()
[1] ‘3.2.5’
> packageVersion("crayon")
[1] ‘1.3.4’
> warningstyle <- crayon::make_style(WarningStyle = rgb(1,0.2,0), bg = FALSE)
> errorstyle <- crayon::make_style(ErrorStyle = "red", bg = FALSE)
> successstyle <- crayon::make_style(SucessStyle = rgb(0,1,0), bg = FALSE)
>
> errorstyle
Crayon style function, ErrorStyle: example output.
> warningstyle
Crayon style function, WarningStyle: example output.
> successstyle
Crayon style function, SucessStyle: example output.
```

**Comment by gaborcsardi** [comment]
Please reopen with a reproducible example if this is still a problem for you. Thanks!
