### ISSUE TITLE
Output not colored in xterm and gnome-terminal

### ISSUE THREAD

**Issue by alaindanet** [r-lib/crayon#68]
Hi,

`crayon v 1.3.4` does not work in my R v3.4.3 running in gnome-terminal v3.22.2 or xterm.

```
> library(crayon)                                                                                             
> cat(blue("Hello", "world!\n"))                                                                              
34mHello world!                                                                                               
39m> 
> num_colors()                                                                                                
[1] 256 
```
```                                                                                        
platform       x86_64-pc-linux-gnu                                                                          
arch           x86_64                                                                                       
os             linux-gnu                                                                                    
system         x86_64, linux-gnu
status                                                                                                      
major          3                                                                                            
minor          4.3
year           2017
month          11                                                                                           
day            30                                                                                           
svn rev        73796
language       R                                                                                            
version.string R version 3.4.3 (2017-11-30)                                                                 
   35 nickname       Kite-Eating Tree
```

Thank you so much for your help!

**Comment by gaborcsardi** [comment]
This does not seem to be a crayon error to me, the terminal simply does not interpret the colors. E.g. try 
```r
cat("\033[34mfoobar\033[39m")
```
Does this come out as blue?

**Comment by alaindanet** [comment]
Thank you very for your help!
However, it did not come out as in color either in `gnome-terminal` and `xterm`.
```
> library(crayon)                                                                                             
> cat("\033[34mfoobar\033[39m")                                                                               
34mfoobar39m>
```

**Comment by gaborcsardi** [comment]
Yeah, that's the thing, the problem is not with crayon, it is seemingly with your terminal or terminal settings.

**Comment by alaindanet** [comment]
Well, here is the summary of the various test that I ran.

- My terminal supports colors:

![color_support](https://user-images.githubusercontent.com/11349327/38194564-8a9cbb16-3678-11e8-86ff-ae4b67b030f6.png) 

- In R, [`colorout`](https://github.com/jalvesaq/colorout) which provides
  colored output in R console, is working well:
```r
library(crayon)
cat(blue("test"))

library(colorout)
rnorm(5)
noColorOut()
rnorm(5)  
```
The previous command lines gives:

![colored_output](https://user-images.githubusercontent.com/11349327/38194795-15df69fc-367a-11e8-8852-fd43cd372737.png)

BUT, the two packages are actually incompatibles:
```r
library(colorout) # ColorOut activated
library(crayon, help)
cat(blue("Hello", "world!\n"))
noColorOut() # Colorout inactivated
cat(blue("Hello", "world!\n"))
```
gives: 
![colored_output2](https://user-images.githubusercontent.com/11349327/38195056-d2021f5c-367b-11e8-919b-687639391721.png)

When `colorout` is activated, `crayon` is not working!

Thank you so much for your help!

**Comment by gaborcsardi** [comment]
It is a bug in colorout then. It assumes that the output is not colored.

**Comment by alaindanet** [comment]
Yes, I will notify the maintainer of the package.

**Comment by alaindanet** [comment]
The problem was fixed after updating `colorout` to the version `1.2.0`.

**Comment by gaborcsardi** [comment]
Cool.
