### ISSUE TITLE
Crayon prints escape sequences, does not apply colors in neovim-qt :terminal

### ISSUE THREAD

**Issue by wngrtn** [r-lib/crayon#75]
I am on Win10, neovim 3.1 and neovim-qt. When I use `:terminal` to run `ls --color=always` I get nicely colored output. When I open `R` and run `library(tidyverse)`, which uses `crayon`, I see escape sequences instead of colors:

    -- ?[1mAttaching packages?[22m --------------------------------------- tidyverse 1.2.1 --
    ?[32mv?[39m ?[34mggplot2?[39m 3.0.0     ?[32mv?[39m ?[34mpurrr  ?[39m 0.2.5
    ?[32mv?[39m ?[34mtibble ?[39m 1.4.2     ?[32mv?[39m ?[34mdplyr  ?[39m 0.7.7
    ?[32mv?[39m ?[34mtidyr  ?[39m 0.8.1     ?[32mv?[39m ?[34mstringr?[39m 1.3.1
    ?[32mv?[39m ?[34mreadr  ?[39m 1.1.1     ?[32mv?[39m ?[34mforcats?[39m 0.3.0

Is neovim-qt :terminal on Windows not supported or am I doing something wrong? If this is not the right place to address this issue, could you point in the right direction?

**Comment by gaborcsardi** [comment]
My guess  is that most probably vim uses something like https://github.com/adoxa/ansicon.

**Comment by gaborcsardi** [comment]
Closing this, please reopen if you still think that there is a problem with crayon.

**Comment by wngrtn** [comment]
I spent a bit more time trying to diagnose this and it does not appear to be a vim problem. I see the same output in cmd, R Gui, vim terminal, neovim termin, neovim-qt terminal. I am not sure about R Gui, but all other options have support for ANSI escape sequences.

I tried running the [color test cmd by Michele Locati](https://gist.github.com/mlocati/fdabcaeb8071d5c75a2d51712db24011#file-win10colors-cmd) in all of the terminals and it worked fine.

**Comment by wngrtn** [comment]
To reproduce, open a Windows terminal in cmd, cmder, in neovim via `:terminal`, or in neovim-qt via `:terminal`, then

```
"c:\Program Files\R\R-3.5.1\bin\x64\R.exe"
install.packages('crayon')
library(crayon)
cat(blue("Hello", "world!\n"))
```

the result is

![grafik](https://user-images.githubusercontent.com/2025721/48477633-65c83b80-e802-11e8-939d-5147dd1ed5f5.png)

Output of `sessionInfo()`:

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C
[5] LC_TIME=German_Germany.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] crayon_1.3.4

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1
```

**Comment by gaborcsardi** [comment]
neovim terminal does not seem to support  ansi colors for me:
<img width="676" alt="screen shot 2018-11-14 at 11 16 31 am" src="https://user-images.githubusercontent.com/660288/48479330-e2f1b180-e7fe-11e8-8c4a-3c8e5063997e.png">

**Comment by wngrtn** [comment]
I get the same result, but if I cat into a cmd file and run it, that does work. How are the two different?

![grafik](https://user-images.githubusercontent.com/2025721/48480674-7f21b580-e80b-11e8-8970-4eb3e0941a56.png)

Please forgive my complete lack of knowledge about how escape sequences work ...

**Comment by wngrtn** [comment]
Ahh, the `echo` statement seems to flip some sort of switch. After running the `cmd` file, your original example works as well:

![grafik](https://user-images.githubusercontent.com/2025721/48481297-497dcc00-e80d-11e8-8f2e-eeda095b0cd9.png)

**Comment by wngrtn** [comment]
It looks as if this is related to the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag, but I am not sure where it should ideally be set and when.

I found a small C gist by Michele Locati. As a workaround, I adopted it into a small program that enables color support and that I call via `system()` in my `.Rprofile`.
