### ISSUE TITLE
R terminal messages in colors like in the colorout package?

### ISSUE THREAD

**Issue by mo0zi** [r-lib/crayon#82]
Hi

Would it be possible to enable the `crayon` package to display messages within the R terminal in colors depending on the data type (or type of message) as it is possible with the `colorout` package?

For example, if I hit
```
> a
Error: object 'a' not found
```
in the R terminal, the default color of the text "Error: object 'a' not found" is the color of the used terminal (e.g. black). When the `colorout` package is loaded, the text can appear in, for example, red.

Unfortunately, the `colorout` package interferes with the colored output of other functions, for example, `devtools::install_github()`.

Thank you very much

**Comment by gaborcsardi** [comment]
Sorry, not possible.
