### ISSUE TITLE
Get the code ansi with the word

### ISSUE THREAD

**Issue by Idriss0peaccel** [r-lib/crayon#85]
Hello,

I would like to know how to have the code ansi + word instead of the word colored

for example:
crayon :: red ("hello") we get that  <span style="color: #f5091e">hello</span> 
but what I want to have is something like this
function_red_ansi("hello) and we get this "\ 033 [31mhello \ 033 [39m"

**Comment by gaborcsardi** [comment]
THat is actually what you get, it is just printed differently. E.g.
```
❯ x <- crayon :: red ("hello")
❯ c(x)
[1] "\033[31mhello\033[39m"
❯ x == "\033[31mhello\033[39m"
[1] TRUE
```
