### ISSUE TITLE
Background color carries over if it is too light  of grey

### ISSUE THREAD

**Issue by EmilHvitfeldt** [r-lib/crayon#91]
I have isolated the issue to start at #F8F8F8. 

```r
library(crayon)
x <- "#F8F8F8FF"

text <- make_style("#000000", bg = FALSE)
background <- make_style(x, bg = TRUE, colors = 256, 
    grey = FALSE)

whiteness <- combine_styles(text, background)

cat(whiteness("this is a test"), "hello")
cat("this is a test", whiteness("hello"))

x <- "#F7F3F7FF"

text <- make_style("#000000", bg = FALSE)
background <- make_style(x, bg = TRUE, colors = 256, 
    grey = FALSE)

whiteness <- combine_styles(text, background)

cat(whiteness("this is a test"), "hello")
cat("this is a test", whiteness("hello"))
```

<img width="498" alt="Screen Shot 2020-01-23 at 4 16 13 PM" src="https://user-images.githubusercontent.com/14034784/73035071-c89c6600-3dfb-11ea-8e38-dc1b52d8a7a1.png">

Appears to only be an issue if the background is truly grayscale 

```r
x <- "#FEFFFFFF"

text <- make_style("#000000", bg = FALSE)
background <- make_style(x, bg = TRUE, colors = 256, 
    grey = FALSE)

whiteness <- combine_styles(text, background)

cat(whiteness("this is a test"), "hello")
cat("this is a test", whiteness("hello"))
```

<img width="449" alt="Screen Shot 2020-01-23 at 4 18 43 PM" src="https://user-images.githubusercontent.com/14034784/73035165-15803c80-3dfc-11ea-9819-3e3f365590e1.png">

**Comment by gaborcsardi** [comment]
I can't reproduce this, I suspect that it is a bug in your terminal or GUI.

**Comment by gaborcsardi** [comment]
So do you know where are problem is?

**Comment by EmilHvitfeldt** [comment]
I was able to isolate it to RStudio, but not quite sure where to go from there.

**Comment by gaborcsardi** [comment]
Reported: https://github.com/rstudio/rstudio/issues/6092

**Comment by gaborcsardi** [comment]
Fixed now in RStudio.
