### ISSUE TITLE
Using crayon in an R package - R CMD check:  'must use only ASCII characters'

### ISSUE THREAD

**Issue by jrosen48** [r-lib/crayon#93]
Hi, I am sure this is an issue you have thought through and addressed, but I didn't see this on a first pass through past and present issues, and so hope you don't mind me asking. I am trying to use crayon in an R package, but am running into a warning when running `R CMD check`:

```{r}
portable packages must use only ASCII characters in their R code,
  except perhaps in comments.
  Use \uxxxx escapes for other characters.
```

The issue seems to be in lines using `crayon::underline()` - am I doing something incorrectly, or could you point me toward documentation or resources that would help me to resolve this? Thanks so much.

**Comment by gaborcsardi** [comment]
crayon markup only uses ASCII characters, AFAIK, so I suspect that your issue is not with crayon.

**Comment by jrosen48** [comment]
thx

**Comment by jrosen48** [comment]
it was an errant, non-standard quotation mark, not to do with crayon
