### ISSUE TITLE
Format data.frame?

### ISSUE THREAD

**Issue by zx8754** [r-lib/crayon#94]
Related SO post:
 - [underline column names in R](https://stackoverflow.com/q/60546084/680068)

**Comment by gaborcsardi** [comment]
I am sorry, but I don't know what this issue is about.

**Comment by zx8754** [comment]
Maybe it was never designed to work with _dataframe_ print method, but here is what that linked post means:

```R
library(crayon)

#example dataframe, with underlined column names
d <- data.frame(mycol1 = 1:3, mycol2 = letters[1:3])
colnames(d) <- c(underline("newcol1"), underline("newcol2"))

#works fine
cat(colnames(d))
```

![image](https://user-images.githubusercontent.com/5212915/102465044-12f68900-4045-11eb-9f7f-f99a2b877a61.png)

Doesn't work when printed as dataframe.
```R
print(d)
cat(d)
```

![image](https://user-images.githubusercontent.com/5212915/102465116-299ce000-4045-11eb-99d3-6426d0f86f31.png)

Print method suggested by Konrad, kind of works - column names and values do not line up, but they do get underlined:
```R
print.data.frame = function (x, ...) {
  output = capture.output(base::print.data.frame(x, ...))
  colnames = crayon::underline(colnames(x))
  regmatches(output[1L], gregexpr('\\S+', output[1L]))[[1L]] = colnames
  cat(output, sep = '\n')
}

d
```

![image](https://user-images.githubusercontent.com/5212915/102465156-3a4d5600-4045-11eb-8762-1c53ed347c28.png)

**Comment by gaborcsardi** [comment]
> ```
> colnames(d) <- c(underline("newcol1"), underline("newcol2"))
> ```

Base R and packages will have all kinds of trouble if you do that. E.g. you can't even call `d$newcol1` any more. This is not up to crayon. 

If you want to customize data frame printing, then indeed a `print.data.frame` method is the way to go. You can modify that print method to line up the column names if you want. Or you can just use tibbles, which have a nice print method.
