### ISSUE TITLE
tibbles in github README

### ISSUE THREAD

**Issue by MyKo101** [r-lib/crayon#96]
I also posted this issue on the `pillar` github page [here](https://github.com/r-lib/pillar/issues/188#issue-638642943)

I have recently uploaded a package to github and used github actions to render my `README.Rmd` file into `README.md`.  Unfortunately, `crayon`-style wrappers are appearing in the output for any `tibble`s displayed in the`README`. They aren't in any local render of the `README.Rmd` file, or on the `pkgdown` site for my package. The output seems to be the wrappers associated with a console output (e.g. `\033[90m`), but they should be the html ones. I believe there is some global option being set incorrectly somewhere, but unfortunately I don't know the internal structure of `crayons` and `pillar` enough to figure it out.

I added an example to another package as an MWE. I stripped my README render action down so it only installs `rmarkdown` and `tibble` (and dependencies) and it is still happening. Here are the outputs:

``` r
library(tibble)
tibble(x=runif(10),y=runif(10))
#> [90m# A tibble: 10 x 2[39m
#>         x     y
#>     [3m[90m<dbl>[39m[23m [3m[90m<dbl>[39m[23m
#> [90m 1[39m 0.309  0.214
#> [90m 2[39m 0.218  0.545
#> [90m 3[39m 0.490  0.567
#> [90m 4[39m 0.083[4m4[24m 0.291
#> [90m 5[39m 0.131  0.106
#> [90m 6[39m 0.299  0.688
#> [90m 7[39m 0.928  0.276
#> [90m 8[39m 0.747  0.841
#> [90m 9[39m 0.383  0.656
#> [90m10[39m 0.498  0.925
```

Session Info:

``` r
sessionInfo()
#> R version 3.6.3 (2020-02-29)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS Catalina 10.15.5
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] tibble_3.0.1
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.4.6     fansi_0.4.1      utf8_1.1.4       assertthat_0.2.1
#>  [5] crayon_1.3.4     digest_0.6.25    lifecycle_0.2.0  magrittr_1.5    
#>  [9] evaluate_0.14    pillar_1.4.4     cli_2.0.2        rlang_0.4.6     
#> [13] stringi_1.4.6    vctrs_0.3.1      ellipsis_0.3.1   rmarkdown_2.2   
#> [17] tools_3.6.3      stringr_1.4.0    glue_1.4.1       xfun_0.14       
#> [21] yaml_2.2.1       compiler_3.6.3   pkgconfig_2.0.3  htmltools_0.4.0 
#> [25] knitr_1.28
```
links:
[Outputs on MWE package](https://github.com/MyKo101/mutils#testing-tibbles)
[github action workflow on MWE package](https://github.com/MyKo101/mutils/blob/master/.github/workflows/render-readme.yaml)
[github action run on MWE package](https://github.com/MyKo101/mutils/runs/771780046?check_suite_focus=true)

**Comment by MyKo101** [comment]
After investigating further, it seems that somewhere the `"crayon.enabled"` option is being set to `TRUE`, and that triggers `has_color()` to return `TRUE`

**Comment by gaborcsardi** [comment]
I am afraid that crayon cannot do much about this, if `crayon.enabled` is `TRUE`, then it will output the escape sequences.

**Comment by MyKo101** [comment]
I understand this isn't `crayon`'s fault. I've added a workaround in my README.Rmd file to reset `crayon.enabled` to be `NULL` (so that `has_color()` can figure it out itself depending on context).

But this definitely feels like an annoying workaround. Wish I knew where the value was being set in the global environment (is it the different OS?). I'll close the issue now, but if I figure it out, I may add a further comment for people looking into this in the future.

**Comment by mrchypark** [comment]
@MyKo101 you save me. Thanks!
