### ISSUE TITLE
num_colors returns 1 in rstudio

### ISSUE THREAD

**Issue by january3** [r-lib/crayon#97]
In the current versions (crayon from CRAN + rstudio) `num_colors` returns 1, which results in only using the basic colors in an rstudio session. 

Same thing happens when one tries to use crayon in combination with fansi::sgr_to_html within rmarkdown. 

Is there a way to force crayon to use the 255 colors, even if it (incorrectly) thinks that the terminal does not support it?

I am developing a package for coloring data frame output (january3/colorDF on github) and since it relies on crayon, it does not render correctly in rstudio. Which is a bummer.

**Comment by gaborcsardi** [comment]
![crayon-rs](https://user-images.githubusercontent.com/660288/85524180-d1d66c80-b5ff-11ea-9e22-89357be80450.png)

So you will need to tell me your RStudio version, and also how you load crayon. In particular, do you load it from your R profile?

See `?crayon::has_color` and `?crayon::num_colors` for a way to force the number of colors.

**Comment by january3** [comment]
Rstudio 1.2.5024 (a couple of weeks old)
crayon 1.3.4 from CRAN.
The crayon package is either loaded directly with a library call or when I am loading my package ("colorDF").

(for different reasons, I need to use the CRAN version of your otherwise excellent package).

OK, I found now solution to one problem. Basically, here is what I have seen:

![Screenshot from 2020-06-24 11-33-58](https://user-images.githubusercontent.com/11678838/85530970-a27b2c00-b60e-11ea-96e7-1c405b0ef085.png)

I have not found the reason for this, but I did find the cause. This happens *only in rstudio* and *only* if the tibble package is loaded (even though it is not attached) before crayon, and only if is attached through .Rprofile. (in fact, I had a small personal utilities package in my .Rprofile which imports caret which imports ggplot2 which imports tibble which imports crayon).

How to reproduce:

1) put "require(tibble)" in your .Rprofile
2) start rstudio
3) observe (library(crayon) ; num_colors();)

I assume that is because R in rstudio reads .Rprofile before session is interactive, and therefore i_num_colors returns 1 and thus, we got ourselves a bug.

This *is* problematic, because users might have stuff related to tidyverse in their .Rprofiles. 

I think using onAttach rather than onLoad should solve the problem. At least it seemed to work when I modified your code.

Related matter: because you are using `onLoad` rather than `onAttach`, if any crayon objects exist in the .RData loaded, then crayon will ignore any subsequent "options(crayon.colors=...)" calls EVEN if the option is set before calling library(crayon). The cache is already set up and thus i_num_colors is not called.

> options(crayon.colors=1234)
> library(crayon)
> num_colors()
[1] 256

Whereas if you start in the same workspace with `R --vanilla`, you get

> options(crayon.colors=1234)
> library(crayon)
> num_colors()
[1] 1234


I suspect that the weird behavior I observed previously in rstudio has something to do with this issue.

However, In rmarkdown the matter seems to be more complicated, because even after I call num_colors(TRUE) and crayon reconsiders and seems to think that there are 256 colors, it still uses the base colors:

![Screenshot from 2020-06-24 11-42-02](https://user-images.githubusercontent.com/11678838/85532174-c55a1000-b60f-11ea-8443-d0e38cdc1860.png)

I did not have yet time to debug that one.

**Comment by gaborcsardi** [comment]
Colors don't have much to do with whether the session is interactive or not. But otherwise you are right. This is why I asked if you load it from the profile. The problem is that the rstudioapi package that crayon queries is not ready yet when the profile runs.

The GH version of crayon _might_ have a workaround.

**Comment by gaborcsardi** [comment]
I can make a new CRAN release if that helps you.

**Comment by january3** [comment]
That would be great. What about using .onAttach rather than .onLoad? Woud that not be a good solution? Or would it break something? (potentially a packages which only load crayon but not attach the namespace). But why is this call during loading necessary anyway? Why not rely on the first call to `num_colors()` whenever it happens? It's not like it saves a lot of time....

Ummm, OK, I see, cache seems not to be NULL upon first call, but why? This should not happen.

But then, using `<<-` is dangerous anyway because you never know in which frame you will end up. I would suggest another solution for your cache:

```
crayon.env <- new.env(parent=emptyenv())
num_colors <- function(forget=FALSE) {
  if(forget || is.null(crayon.env[["cache"]])) {
    result <- i_num_colors()
    if (sink.number() == 0 && rstudio_initialized()) {
        crayon.env[["cache"]] <- result
    }
  } else { 
      result <- crayon.env[["cache"]]
  }
  result
}
```

No need for closures or `<<-`.
